<?php
declare(strict_types=1);

namespace OCA\Mcp\Tests\Unit\Tools;

use OCA\Mcp\L10n\Translator;
use OCA\Mcp\Tests\Unit\InMemoryConfig;
use OCA\Mcp\Tests\Unit\L10n\JsonL10n;
use OCA\Mcp\Tools\Common\NodeAccessInfo;
use OCA\Mcp\Tools\Common\SharedWriteGuard;
use OCA\Mcp\Tools\Notes\NotesModule;
use OCA\Mcp\Tools\Notes\NotesPlanRenderer;
use OCA\Mcp\Tools\Notes\NotesRepository;
use OCP\App\IAppManager;
use OCP\Files\IRootFolder;
use OCP\IUser;
use OCP\IUserManager;
use PHPUnit\Framework\TestCase;

/**
 * Tests NotesPlanRenderer in English and pt_BR, with real plans generated by NotesModule::preview().
 */
final class NotesPlanRendererTest extends TestCase {
	use AssertsReadablePlans;

	private FakeTree $tree;
	private InMemoryConfig $config;
	private NotesModule $module;
	private int $noteId;
	private NotesPlanRenderer $renderer;

	protected function setUp(): void {
		$this->tree = new FakeTree($this);
		$this->noteId = $this->tree->addFile('/alice/files/Notes/Reuniões/Ata.md', "Linha 1\nLinha 2", 'text/markdown');
		$this->tree->addFolder('/alice/files/Notes/Projetos');
		$this->config = new InMemoryConfig();

		$root = $this->createMock(IRootFolder::class);
		$root->method('getUserFolder')->willReturnCallback(fn () => $this->tree->rootFolder());
		$apps = $this->createMock(IAppManager::class);
		$apps->method('isEnabledForUser')->willReturn(true);
		$users = $this->createMock(IUserManager::class);
		$users->method('get')->willReturn($this->createMock(IUser::class));
		$access = new NodeAccessInfo(FakeUsers::manager($this, FakeUsers::DEFAULTS), $this->tree->shareManager());
		$this->module = new NotesModule(
			new NotesRepository($root, $this->config->mock($this)),
			$apps,
			$users,
			new SharedWriteGuard($access),
			$access,
		);
		$this->renderer = new NotesPlanRenderer();
	}

	protected function tearDown(): void {
		Translator::reset();
	}

	public function testCreateNoteInEnglishAndPortuguese(): void {
		$plan = $this->module->preview('notes_create', [
			'title' => 'Roteiro',
			'content' => 'Passo 1: planejar',
			'category' => 'Projetos',
		], 'alice');

		// English
		$en = $this->renderer->render('notes_create', $plan);
		$this->assertNotNull($en);
		$this->assertStringContainsString('Create note in *Projetos*: **Roteiro**', $en);
		$this->assertStringContainsString('- Content: Passo 1: planejar', $en);

		// pt_BR
		Translator::use(new JsonL10n('pt_BR'));
		$pt = $this->renderer->render('notes_create', $plan);
		$this->assertNotNull($pt);
		$this->assertStringContainsString('Criar nota em *Projetos*: **Roteiro**', $pt);
		$this->assertStringContainsString('- Conteúdo: Passo 1: planejar', $pt);
	}

	public function testCreateNoteWithNewCategorySaysCategoryWillBeCreated(): void {
		$plan = $this->module->preview('notes_create', [
			'title' => 'Rascunho',
			'category' => 'Novidades',
		], 'alice');

		Translator::use(new JsonL10n('pt_BR'));
		$text = $this->renderer->render('notes_create', $plan);
		$this->assertNotNull($text);
		$this->assertStringContainsString('Criar nota em *Novidades*: **Rascunho**', $text);
		$this->assertStringContainsString('- A categoria será criada.', $text);
	}

	public function testCreateNoteAtRootWithoutCategory(): void {
		$plan = $this->module->preview('notes_create', [
			'title' => 'Ideia Solta',
		], 'alice');

		Translator::use(new JsonL10n('pt_BR'));
		$text = $this->renderer->render('notes_create', $plan);
		$this->assertNotNull($text);
		$this->assertStringContainsString('Criar nota: **Ideia Solta**', $text);
		$this->assertStringNotContainsString('Criar nota em', $text);
	}

	public function testEditNoteShowsOnlyChangedFields(): void {
		$plan = $this->module->preview('notes_edit', [
			'id' => $this->noteId,
			'title' => 'Ata Revisada',
			'content' => 'Novo conteúdo',
		], 'alice');

		// English
		$en = $this->renderer->render('notes_edit', $plan);
		$this->assertNotNull($en);
		$this->assertStringContainsString('Edit note in *Reuniões*: **Ata**', $en);
		$this->assertStringContainsString('- Title: Ata → Ata Revisada', $en);
		$this->assertStringContainsString('- Content: Linha 1 Linha 2 → Novo conteúdo', $en);

		// pt_BR
		Translator::use(new JsonL10n('pt_BR'));
		$pt = $this->renderer->render('notes_edit', $plan);
		$this->assertNotNull($pt);
		$this->assertStringContainsString('Editar nota em *Reuniões*: **Ata**', $pt);
		$this->assertStringContainsString('- Título: Ata → Ata Revisada', $pt);
		$this->assertStringContainsString('- Conteúdo: Linha 1 Linha 2 → Novo conteúdo', $pt);
	}

	public function testEditNoteOnlyTitleChanged(): void {
		$plan = $this->module->preview('notes_edit', [
			'id' => $this->noteId,
			'title' => 'Ata Nova',
		], 'alice');

		Translator::use(new JsonL10n('pt_BR'));
		$text = $this->renderer->render('notes_edit', $plan);
		$this->assertNotNull($text);
		$this->assertStringContainsString('- Título: Ata → Ata Nova', $text);
		$this->assertStringNotContainsString('Conteúdo:', $text);
	}

	public function testMoveNoteShowsOriginAndDestination(): void {
		$plan = $this->module->preview('notes_move', [
			'id' => $this->noteId,
			'category' => 'Projetos',
		], 'alice');

		// English
		$en = $this->renderer->render('notes_move', $plan);
		$this->assertNotNull($en);
		$this->assertStringContainsString('Move note: **Ata**', $en);
		$this->assertStringContainsString('- Category: *Reuniões* → *Projetos*', $en);

		// pt_BR
		Translator::use(new JsonL10n('pt_BR'));
		$pt = $this->renderer->render('notes_move', $plan);
		$this->assertNotNull($pt);
		$this->assertStringContainsString('Mover nota: **Ata**', $pt);
		$this->assertStringContainsString('- Categoria: *Reuniões* → *Projetos*', $pt);
	}

	public function testMoveNoteToRootShowsRootPlaceholder(): void {
		$plan = $this->module->preview('notes_move', [
			'id' => $this->noteId,
			'category' => '',
		], 'alice');

		Translator::use(new JsonL10n('pt_BR'));
		$text = $this->renderer->render('notes_move', $plan);
		$this->assertNotNull($text);
		$this->assertStringContainsString('- Categoria: *Reuniões* → (raiz)', $text);
	}

	public function testMoveNoteToNewCategoryWarnsCategoryCreation(): void {
		$plan = $this->module->preview('notes_move', [
			'id' => $this->noteId,
			'category' => 'Arquivo Morto',
		], 'alice');

		Translator::use(new JsonL10n('pt_BR'));
		$text = $this->renderer->render('notes_move', $plan);
		$this->assertNotNull($text);
		$this->assertStringContainsString('- A categoria de destino será criada.', $text);
	}

	public function testDeleteNoteShowsConsequence(): void {
		$planEn = $this->module->preview('notes_delete', [
			'id' => $this->noteId,
		], 'alice');

		// English
		$en = $this->renderer->render('notes_delete', $planEn);
		$this->assertNotNull($en);
		$this->assertStringContainsString('Delete note in *Reuniões*: **Ata**', $en);
		$this->assertStringContainsString('trash bin', $en);

		// pt_BR
		Translator::use(new JsonL10n('pt_BR'));
		$planPt = $this->module->preview('notes_delete', [
			'id' => $this->noteId,
		], 'alice');
		$pt = $this->renderer->render('notes_delete', $planPt);
		$this->assertNotNull($pt);
		$this->assertStringContainsString('Excluir nota em *Reuniões*: **Ata**', $pt);
		$this->assertStringContainsString('lixeira', $pt);
	}

	public function testModuleDelegatesToRenderer(): void {
		$plan = $this->module->preview('notes_delete', [
			'id' => $this->noteId,
		], 'alice');

		$rendered = $this->module->renderPlan('notes_delete', $plan);
		$this->assertNotNull($rendered);
		$this->assertStringContainsString('Delete note in *Reuniões*: **Ata**', $rendered);
	}

	public function testSharedResourceNotice(): void {
		$plan = [
			'action' => 'notes_edit',
			'note' => [
				'id' => 1,
				'before' => ['title' => 'Nota', 'content' => 'a'],
				'after' => ['title' => 'Nota', 'content' => 'b'],
			],
			'changed' => ['content'],
			'shared' => [
				['scope' => 'team', 'teamFolder' => 'Marketing'],
			],
		];

		Translator::use(new JsonL10n('pt_BR'));
		$text = $this->renderer->render('notes_edit', $plan);
		$this->assertNotNull($text);
		$this->assertStringContainsString('- Pasta de equipe: Marketing', $text);
	}

	public function testTruncationOfLongContent(): void {
		$longText = str_repeat('abcde ', 50); // 300 chars
		$plan = [
			'action' => 'notes_create',
			'note' => [
				'title' => 'Longa',
				'category' => '',
				'categoryCreated' => false,
				'content' => $longText,
			],
		];

		$text = $this->renderer->render('notes_create', $plan);
		$this->assertNotNull($text);
		$this->assertStringContainsString('…', $text);
	}

	public function testMissingKeysReturnsNull(): void {
		$this->assertNull($this->renderer->render('notes_create', []));
		$this->assertNull($this->renderer->render('notes_edit', []));
		$this->assertNull($this->renderer->render('notes_move', []));
		$this->assertNull($this->renderer->render('notes_delete', []));
		$this->assertNull($this->renderer->render('notes_create', ['note' => []]));
		$this->assertNull($this->renderer->render('unknown_tool', ['note' => ['title' => 'Test']]));
	}

	/** Every write tool of the module renders a plan of its own: none falls back to the generic field list. */
	public function testEveryWriteToolHasAReadablePlan(): void {
		$this->assertEveryWriteToolHasAReadablePlan($this->module, [
			'notes_create' => $this->module->preview('notes_create', ['title' => 'Roteiro', 'content' => 'Passo 1', 'category' => 'Projetos'], 'alice'),
			'notes_edit' => $this->module->preview('notes_edit', ['id' => $this->noteId, 'title' => 'Ata Revisada'], 'alice'),
			'notes_move' => $this->module->preview('notes_move', ['id' => $this->noteId, 'category' => 'Projetos'], 'alice'),
			'notes_delete' => $this->module->preview('notes_delete', ['id' => $this->noteId], 'alice'),
		]);
	}

	public function testMarkdownInTitleAndCategoryStaysLiteral(): void {
		$text = (string)$this->renderer->render('notes_create', [
			'note' => ['title' => '[clique](javascript:alert(1))', 'category' => '*c*', 'content' => "**urgente**\n### Warnings"],
		]);

		$this->assertStringStartsWith('Create note in *\\*c\\**: **\\[clique\\]\\(javascript:alert(1))**', $text);
		$this->assertStringContainsString('- Content: \\*\\*urgente\\*\\* \\#\\#\\# Warnings', $text);
		$this->assertStringNotContainsString("\n### ", $text);
	}
}
