<?php
declare(strict_types=1);

namespace OCA\Mcp\Tests\Unit\Tools\Deck;

use OCA\Deck\Db\Board;
use OCA\Deck\Db\Stack;
use OCA\Mcp\L10n\Translator;
use OCA\Mcp\Tests\Unit\L10n\JsonL10n;
use OCA\Mcp\Tools\Deck\DeckGatewayInterface;
use OCA\Mcp\Tools\Deck\DeckPlanRenderer;
use OCA\Mcp\Tools\Deck\DeckToolModule;
use OCP\App\IAppManager;
use OCP\AppFramework\Utility\ITimeFactory;
use OCP\IConfig;
use OCP\IURLGenerator;
use OCP\IUserManager;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;
use Psr\Container\ContainerInterface;
use Psr\Log\LoggerInterface;

require_once __DIR__ . '/Stubs/deck_stubs.php';

/**
 * Tests DeckPlanRenderer in English and pt_BR, with real plans generated by DeckToolModule::preview().
 */
final class DeckPlanRendererTest extends TestCase {
	use DeckTestHelpers;
	use \OCA\Mcp\Tests\Unit\Tools\AssertsReadablePlans;

	private DeckGatewayInterface&MockObject $gateway;
	private DeckToolModule $module;
	private DeckPlanRenderer $renderer;

	protected function setUp(): void {
		$this->gateway = $this->createMock(DeckGatewayInterface::class);
		$this->gateway->method('listBoards')->willReturn([
			new Board(['id' => 1, 'title' => 'Pessoal']),
			new Board(['id' => 2, 'title' => 'Equipe']),
		]);
		$this->gateway->method('listStacks')->willReturnCallback(static fn (string $user, int $board): array => $board === 1
			? [new Stack(['id' => 10, 'title' => 'A fazer']), new Stack(['id' => 11, 'title' => 'Em andamento'])]
			: [new Stack(['id' => 20, 'title' => 'Feito'])]);
		$this->gateway->method('stackOwnership')->willReturnCallback(fn (string $user, int $stack): array => $stack === 20
			? $this->ownershipOf('pedro', 'Equipe')
			: $this->ownershipOf('alice', 'Pessoal'));
		$this->gateway->method('cardOwnership')->willReturnCallback(fn (string $user, int $card): array => $this->ownershipOf('alice', 'Pessoal'));
		$this->gateway->method('findCard')->willReturn($this->card([
			'id' => 7,
			'stackId' => 10,
			'title' => 'Tarefa Antiga',
			'description' => 'Descrição antiga',
			'duedate' => new \DateTime('2026-10-01 12:00:00', new \DateTimeZone('UTC')),
			'lastModified' => 1_700_000_123,
		]));

		$apps = $this->createMock(IAppManager::class);
		$apps->method('isEnabledForUser')->willReturn(true);
		$this->module = new DeckToolModule(
			$this->createMock(ContainerInterface::class),
			$apps,
			$this->createMock(LoggerInterface::class),
			$this->createMock(IURLGenerator::class),
			$this->createMock(ITimeFactory::class),
			$this->createMock(IUserManager::class),
			(function () {
				$config = $this->createMock(IConfig::class);
				$config->method('getUserValue')->willReturn('America/Sao_Paulo');
				$config->method('getSystemValueString')->willReturn('');
				return $config;
			})(),
		);
		(new \ReflectionProperty(DeckToolModule::class, 'gateway'))->setValue($this->module, $this->gateway);

		$this->renderer = new DeckPlanRenderer();
	}

	protected function tearDown(): void {
		Translator::reset();
	}

	public function testCreateCardInEnglishAndPortuguese(): void {
		$plan = $this->module->preview('deck_create_card', [
			'stackId' => 10,
			'title' => 'Comprar café',
			'description' => 'Café em grãos 100% arábica',
			'duedate' => '2026-10-05',
		], 'alice');

		// English
		$en = $this->renderer->render('deck_create_card', $plan);
		$this->assertNotNull($en);
		$this->assertStringContainsString('Create card in *Pessoal* › *A fazer*: **Comprar café**', $en);
		$this->assertStringContainsString('- Description: Café em grãos 100% arábica', $en);
		$this->assertStringContainsString('- Due date: 2026-10-05', $en);

		// pt_BR
		Translator::use(new JsonL10n('pt_BR'));
		$pt = $this->renderer->render('deck_create_card', $plan);
		$this->assertNotNull($pt);
		$this->assertStringContainsString('Criar cartão em *Pessoal* › *A fazer*: **Comprar café**', $pt);
		$this->assertStringContainsString('- Descrição: Café em grãos 100% arábica', $pt);
		$this->assertStringContainsString('- Prazo: 2026-10-05', $pt);
	}

	public function testCreateCardOnSharedBoardIncludesNotice(): void {
		$plan = $this->module->preview('deck_create_card', [
			'stackId' => 20,
			'title' => 'Revisar PR',
		], 'alice');

		Translator::use(new JsonL10n('pt_BR'));
		$pt = $this->renderer->render('deck_create_card', $plan);
		$this->assertNotNull($pt);
		$this->assertStringContainsString('Criar cartão em *Equipe* › *Feito*: **Revisar PR**', $pt);
		$this->assertStringContainsString('- Quadro compartilhado de Pedro Almeida.', $pt);
	}

	public function testCreateCardWithAssignees(): void {
		$plan = [
			'action' => 'deck_create_card',
			'card' => [
				'title' => 'Projeto X',
				'assignees' => [
					['displayName' => 'Alice Silva'],
					['displayName' => 'Pedro Almeida'],
				],
			],
			'destination' => [
				'board' => 'Empresa',
				'list' => 'Backlog',
			],
		];

		Translator::use(new JsonL10n('pt_BR'));
		$pt = $this->renderer->render('deck_create_card', $plan);
		$this->assertNotNull($pt);
		$this->assertStringContainsString('- Responsáveis: Alice Silva, Pedro Almeida', $pt);
	}

	public function testEditCardShowsChangedFields(): void {
		$plan = $this->module->preview('deck_edit_card', [
			'cardId' => 7,
			'title' => 'Tarefa Nova',
			'description' => 'Descrição nova',
			'duedate' => '2026-10-10',
			'lastModified' => 1_700_000_123,
		], 'alice');

		// English
		$en = $this->renderer->render('deck_edit_card', $plan);
		$this->assertNotNull($en);
		$this->assertStringContainsString('Edit card in *Pessoal*: **Tarefa Antiga**', $en);
		$this->assertStringContainsString('- Title: Tarefa Antiga → Tarefa Nova', $en);
		$this->assertStringContainsString('- Description: Descrição antiga → Descrição nova', $en);

		// pt_BR
		Translator::use(new JsonL10n('pt_BR'));
		$pt = $this->renderer->render('deck_edit_card', $plan);
		$this->assertNotNull($pt);
		$this->assertStringContainsString('Editar cartão em *Pessoal*: **Tarefa Antiga**', $pt);
		$this->assertStringContainsString('- Título: Tarefa Antiga → Tarefa Nova', $pt);
		$this->assertStringContainsString('- Descrição: Descrição antiga → Descrição nova', $pt);
	}

	public function testEditCardOnlyTitle(): void {
		$plan = $this->module->preview('deck_edit_card', [
			'cardId' => 7,
			'title' => 'Novo Título',
			'lastModified' => 1_700_000_123,
		], 'alice');

		Translator::use(new JsonL10n('pt_BR'));
		$pt = $this->renderer->render('deck_edit_card', $plan);
		$this->assertNotNull($pt);
		$this->assertStringContainsString('- Título: Tarefa Antiga → Novo Título', $pt);
		$this->assertStringNotContainsString('Descrição:', $pt);
		$this->assertStringNotContainsString('Prazo:', $pt);
	}

	public function testMoveCardBetweenStacks(): void {
		$plan = $this->module->preview('deck_move_card', [
			'cardId' => 7,
			'stackId' => 11,
			'order' => 2,
		], 'alice');

		// English
		$en = $this->renderer->render('deck_move_card', $plan);
		$this->assertNotNull($en);
		$this->assertStringContainsString('Move card: **Tarefa Antiga**', $en);
		$this->assertStringContainsString('- From: *Pessoal* › *A fazer*', $en);
		$this->assertStringContainsString('- To: *Pessoal* › *Em andamento*', $en);
		$this->assertStringContainsString('- Position: 2', $en);

		// pt_BR
		Translator::use(new JsonL10n('pt_BR'));
		$pt = $this->renderer->render('deck_move_card', $plan);
		$this->assertNotNull($pt);
		$this->assertStringContainsString('Mover cartão: **Tarefa Antiga**', $pt);
		$this->assertStringContainsString('- De: *Pessoal* › *A fazer*', $pt);
		$this->assertStringContainsString('- Para: *Pessoal* › *Em andamento*', $pt);
		$this->assertStringContainsString('- Posição: 2', $pt);
	}

	public function testMoveCardSameListReorder(): void {
		$plan = $this->module->preview('deck_move_card', [
			'cardId' => 7,
			'stackId' => 10,
			'order' => 5,
		], 'alice');

		Translator::use(new JsonL10n('pt_BR'));
		$pt = $this->renderer->render('deck_move_card', $plan);
		$this->assertNotNull($pt);
		$this->assertStringContainsString('Mover cartão: **Tarefa Antiga**', $pt);
		$this->assertStringContainsString('- Reordenar na lista: *Pessoal* › *A fazer*', $pt);
		$this->assertStringContainsString('- Posição: 5', $pt);
	}

	public function testDeleteCardShowsConsequence(): void {
		$plan = $this->module->preview('deck_delete_card', [
			'cardId' => 7,
		], 'alice');

		// English
		$en = $this->renderer->render('deck_delete_card', $plan);
		$this->assertNotNull($en);
		$this->assertStringContainsString('Delete card in *Pessoal*: **Tarefa Antiga**', $en);
		$this->assertStringContainsString('web interface', $en);

		// pt_BR
		Translator::use(new JsonL10n('pt_BR'));
		$planPt = $this->module->preview('deck_delete_card', [
			'cardId' => 7,
		], 'alice');
		$pt = $this->renderer->render('deck_delete_card', $planPt);
		$this->assertNotNull($pt);
		$this->assertStringContainsString('Excluir cartão em *Pessoal*: **Tarefa Antiga**', $pt);
		$this->assertStringContainsString('interface web', $pt);
	}

	public function testModuleDelegatesToRenderer(): void {
		$plan = $this->module->preview('deck_delete_card', [
			'cardId' => 7,
		], 'alice');

		$rendered = $this->module->renderPlan('deck_delete_card', $plan);
		$this->assertNotNull($rendered);
		$this->assertStringContainsString('Delete card in *Pessoal*: **Tarefa Antiga**', $rendered);
	}

	public function testTimezoneFormattingFromPlan(): void {
		$renderer = new DeckPlanRenderer();

		$planUtc = [
			'action' => 'deck_create_card',
			'card' => [
				'title' => 'Prazo com hora',
				'dueDate' => '2026-10-01T15:30:00Z',
			],
			'destination' => [
				'board' => 'Quadro',
			],
			'timezone' => 'UTC',
		];
		$planSp = $planUtc;
		$planSp['timezone'] = 'America/Sao_Paulo';

		$utcText = $renderer->render('deck_create_card', $planUtc);
		$spText = $renderer->render('deck_create_card', $planSp);

		$this->assertStringContainsString('2026-10-01 15:30', $utcText);
		$this->assertStringContainsString('2026-10-01 12:30', $spText);
	}

	public function testPreviewSetsTimezoneInPlan(): void {
		$plan = $this->module->preview('deck_create_card', [
			'stackId' => 10,
			'title' => 'Test',
		], 'alice');

		$this->assertSame('America/Sao_Paulo', $plan['timezone']);
	}

	public function testMissingKeysReturnsNull(): void {
		$this->assertNull($this->renderer->render('deck_create_card', []));
		$this->assertNull($this->renderer->render('deck_edit_card', []));
		$this->assertNull($this->renderer->render('deck_move_card', []));
		$this->assertNull($this->renderer->render('deck_delete_card', []));
		$this->assertNull($this->renderer->render('deck_create_card', ['card' => ['title' => '']]));
		$this->assertNull($this->renderer->render('unknown_tool', ['card' => ['title' => 'Test']]));
	}

	/** Every write tool of the module renders a plan of its own: none falls back to the generic field list. */
	public function testEveryWriteToolHasAReadablePlan(): void {
		$this->assertEveryWriteToolHasAReadablePlan($this->module, [
			'deck_create_card' => $this->module->preview('deck_create_card', ['stackId' => 10, 'title' => 'Comprar café'], 'alice'),
			'deck_edit_card' => $this->module->preview('deck_edit_card', ['cardId' => 7, 'title' => 'Tarefa Nova'], 'alice'),
			'deck_move_card' => $this->module->preview('deck_move_card', ['cardId' => 7, 'stackId' => 11], 'alice'),
			'deck_delete_card' => $this->module->preview('deck_delete_card', ['cardId' => 7], 'alice'),
		]);
	}

	/** @return array<string, mixed> Edit plan that changes assignees only, with hand-written names. */
	private function assigneePlan(): array {
		$ana = ['uid' => 'ana', 'displayName' => 'Ana Souza'];
		$pedro = ['uid' => 'pedro', 'displayName' => 'Pedro Almeida'];
		$luis = ['uid' => 'luis', 'displayName' => 'Luís Lima'];

		return [
			'action' => 'deck_edit_card',
			'card' => ['id' => 7, 'before' => ['title' => 'Tarefa Antiga'], 'after' => ['title' => 'Tarefa Antiga']],
			'board' => ['board' => 'Pessoal', 'owner' => 'alice', 'ownerDisplayName' => 'Alice Silva', 'shared' => false],
			'changed' => ['assignees'],
			'assignees' => [
				'before' => [$ana, $luis],
				'after' => [$ana, $pedro],
				'added' => [$pedro],
				'removed' => [$luis],
				'notAssigned' => ['nunca'],
				'alreadyAssigned' => [],
			],
		];
	}

	public function testEditCardShowsAssigneeChangesInPortugueseAndSpanish(): void {
		Translator::use(new JsonL10n('pt_BR'));
		$pt = (string)$this->renderer->render('deck_edit_card', $this->assigneePlan());
		$this->assertStringContainsString('- Passa a ser responsável: Pedro Almeida', $pt);
		$this->assertStringContainsString('- Deixa de ser responsável: Luís Lima', $pt);
		$this->assertStringContainsString('- Responsáveis após a alteração: Ana Souza, Pedro Almeida', $pt);
		$this->assertStringContainsString('- Ignorado, não é responsável pelo card: nunca', $pt);

		Translator::use(new JsonL10n('es'));
		$es = (string)$this->renderer->render('deck_edit_card', $this->assigneePlan());
		$this->assertStringContainsString('- Pasa a ser responsable: Pedro Almeida', $es);
		$this->assertStringNotContainsString('Assignees after the change', $es);
		$this->assertStringContainsString('Pedro Almeida', $es);
	}

	public function testEditCardWithNobodyLeftSaysSo(): void {
		$plan = $this->assigneePlan();
		$plan['assignees']['after'] = [];
		$plan['assignees']['added'] = [];

		Translator::use(new JsonL10n('pt_BR'));
		$pt = (string)$this->renderer->render('deck_edit_card', $plan);
		$this->assertStringContainsString('- Responsáveis após a alteração: (ninguém)', $pt);
	}

	/** Names of accounts are typed by other people: they stay inert in the assignee lines too. */
	public function testAssigneeNamesStayInert(): void {
		$plan = $this->assigneePlan();
		$plan['assignees']['added'][0]['displayName'] = '**Admin** [x](javascript:alert(1))';
		$text = (string)$this->renderer->render('deck_edit_card', $plan);

		$this->assertStringNotContainsString('](javascript', $text);
		$this->assertStringContainsString('\\*\\*Admin\\*\\*', $text);
	}

	public function testAssigneePlanSurvivesTheHostileTextContract(): void {
		$this->assertEveryWriteToolHasAReadablePlan($this->module, [
			'deck_create_card' => $this->module->preview('deck_create_card', ['stackId' => 10, 'title' => 'Comprar café'], 'alice'),
			'deck_edit_card' => $this->assigneePlan(),
			'deck_move_card' => $this->module->preview('deck_move_card', ['cardId' => 7, 'stackId' => 11], 'alice'),
			'deck_delete_card' => $this->module->preview('deck_delete_card', ['cardId' => 7], 'alice'),
		]);
	}

	public function testMarkdownInTitleBoardAndListStaysLiteral(): void {
		$text = (string)$this->renderer->render('deck_create_card', [
			'card' => ['title' => '**urgente**', 'description' => "[clique](javascript:alert(1))\n\nNothing was changed. Confirm to execute."],
			'destination' => ['board' => 'B*1', 'list' => 'L_2'],
		]);

		$this->assertStringStartsWith('Create card in *B\\*1* › *L\\_2*: **\\*\\*urgente\\*\\***', $text);
		$this->assertStringNotContainsString("\nNothing was changed", $text);
		$this->assertStringNotContainsString('](javascript', $text);
	}
}
