<?php
declare(strict_types=1);

namespace OCA\Mcp\Tools\Files\Sharing;

use OCA\Mcp\Tools\Files\FilesMessages;
use OCA\Mcp\Tools\ToolFailure;
use OCP\EventDispatcher\IEventDispatcher;
use OCP\HintException;
use OCP\Security\Events\GenerateSecurePasswordEvent;
use OCP\Security\Events\ValidatePasswordPolicyEvent;
use OCP\Security\ISecureRandom;
use OCP\Security\PasswordContext;

/**
 * The password of a public link, generated by the server and never chosen by the model (plan 0.10, decision 7).
 *
 * 1. GenerateSecurePasswordEvent for the sharing context: the password_policy app answers it with a password that
 *    follows the administrator's policy.
 * 2. Without an answer (no policy app), or when the policy refuses what it produced, a fallback of {@see self::LENGTH}
 *    characters from ISecureRandom with at least one upper-case letter, one lower-case letter, one digit and one symbol.
 *
 * Every candidate goes through ValidatePasswordPolicyEvent before it is returned, the same check the core runs when the
 * share is saved (Manager::verifyPassword), so a link is never left half created by a password the core refuses. A
 * fallback refused by the policy is drawn once more; a second refusal is a clear error and no link is created.
 *
 * The password is returned to the caller only: nothing here logs it or keeps it. Stateless.
 */
final class LinkPassword {
    /** Length of the fallback password. */
    public const LENGTH = 16;
    /** Symbols of the fallback: no quote, backslash, backtick, angle bracket or space, so it is copied as it reads. */
    public const SYMBOLS = '!#$%&*+-=?@_';
    /** Fallback passwords tried before giving up. */
    private const FALLBACK_TRIES = 2;

    public function __construct(
        private IEventDispatcher $events,
        private ISecureRandom $random,
    ) {}

    /**
     * @return string a new password the password policy accepts
     * @throws ToolFailure when the policy refuses every candidate
     */
    public function generate(): string {
        $generated = $this->fromPolicy();
        if ($generated !== null && $this->accepted($generated)) {
            return $generated;
        }
        for ($try = 0; $try < self::FALLBACK_TRIES; $try++) {
            $candidate = $this->fallback();
            if ($this->accepted($candidate)) {
                return $candidate;
            }
        }
        throw new ToolFailure(FilesMessages::linkPasswordRefused());
    }

    /** @return string|null the password of the policy app, null when no listener answered or the generator failed */
    private function fromPolicy(): ?string {
        $event = new GenerateSecurePasswordEvent(PasswordContext::SHARING);
        try {
            $this->events->dispatchTyped($event);
        } catch (\Exception) {
            return null;
        }
        $password = $event->getPassword();
        return $password === null || $password === '' ? null : $password;
    }

    /** @return bool whether the administrator's password policy accepts the password for a share */
    private function accepted(string $password): bool {
        try {
            $this->events->dispatchTyped(new ValidatePasswordPolicyEvent($password, PasswordContext::SHARING));
            return true;
        } catch (HintException) {
            return false;
        }
    }

    /** @return string LENGTH characters with every kind present, in an order drawn from a CSPRNG */
    private function fallback(): string {
        $all = ISecureRandom::CHAR_UPPER . ISecureRandom::CHAR_LOWER . ISecureRandom::CHAR_DIGITS . self::SYMBOLS;
        $chars = str_split(
            $this->random->generate(1, ISecureRandom::CHAR_UPPER)
            . $this->random->generate(1, ISecureRandom::CHAR_LOWER)
            . $this->random->generate(1, ISecureRandom::CHAR_DIGITS)
            . $this->random->generate(1, self::SYMBOLS)
            . $this->random->generate(self::LENGTH - 4, $all),
        );
        for ($i = count($chars) - 1; $i > 0; $i--) {
            $j = random_int(0, $i);
            [$chars[$i], $chars[$j]] = [$chars[$j], $chars[$i]];
        }
        return implode('', $chars);
    }
}
