<?php
declare(strict_types=1);

/**
 * Writes tests/fixtures/nextcloud-api/<major>.php: the public surface, in that release, of every Nextcloud class the
 * app names in lib/ plus NextcloudApiUsage::EXTRA_CLASSES. NextcloudApiContractTest reads these files; nothing in the
 * test suite reads a Nextcloud source tree.
 *
 * Usage: php tests/fixtures/nextcloud-api/generate.php <major> <tree>
 *
 * <tree> is a nextcloud/server checkout of the release in NextcloudApiUsage::SOURCES (lib/public, lib/private/Hooks,
 * lib/base.php, lib/OC.php from 35 on, and apps/dav, apps/files_versions, apps/files_trashbin, apps/files_sharing are enough), with the
 * nextcloud/deck and nextcloud/spreed tags of that row checked out under apps/deck and apps/spreed. The script refuses
 * a tree whose versions differ from that row.
 */

use OCA\Mcp\Tests\Unit\Contract\NextcloudApi\LibScanner;
use OCA\Mcp\Tests\Unit\Contract\NextcloudApi\NextcloudApiUsage;
use OCA\Mcp\Tests\Unit\Contract\NextcloudApi\SourceParser;

require __DIR__ . '/../../../vendor/autoload.php';

[, $major, $tree] = $argv + [null, null, null];
$expected = NextcloudApiUsage::SOURCES[$major] ?? null;
if ($expected === null || $tree === null || !is_dir($tree)) {
    fwrite(STDERR, "usage: php generate.php <major of NextcloudApiUsage::SOURCES> <tree>\n");
    exit(2);
}

/** @return string the <version> of an app's appinfo/info.xml */
$appVersion = static fn (string $app): string => (string)(simplexml_load_file("$tree/apps/$app/appinfo/info.xml")->version ?? '');
$OC_VersionString = '';
require "$tree/version.php";
$found = ['server' => $OC_VersionString, 'deck' => $appVersion('deck'), 'spreed' => $appVersion('spreed')];
if ($found !== $expected) {
    fwrite(STDERR, 'tree holds ' . json_encode($found) . ', expected ' . json_encode($expected) . "\n");
    exit(1);
}

$classes = array_keys((new LibScanner(dirname(__DIR__, 3) . '/lib'))->classes());
$classes = array_values(array_unique([...$classes, ...NextcloudApiUsage::EXTRA_CLASSES, ...array_map(
    static fn (array $gate): string => explode('::', $gate['fallback'])[0],
    NextcloudApiUsage::VERSION_GATED,
)]));
sort($classes);

$parser = new SourceParser($tree);
$surfaces = [];
foreach ($classes as $class) {
    $surfaces[$class] = $parser->surface($class);
}

/** @return string a value as a one-line PHP literal: short arrays, lists without their keys */
$literal = static function (mixed $value) use (&$literal): string {
    if (!is_array($value)) {
        return var_export($value, true);
    }
    $items = array_map(
        static fn ($key, $item): string => (array_is_list($value) ? '' : var_export($key, true) . ' => ') . $literal($item),
        array_keys($value),
        $value,
    );
    return '[' . implode(', ', $items) . ']';
};
$lines = array_map(static fn (string $class, ?array $surface): string => '        ' . var_export($class, true) . ' => ' . $literal($surface) . ',',
    array_keys($surfaces), $surfaces);
$php = "<?php\n// Generated by tests/fixtures/nextcloud-api/generate.php from nextcloud/server v{$found['server']}, "
    . "nextcloud/deck v{$found['deck']} and nextcloud/spreed v{$found['spreed']}. Do not edit by hand.\n"
    . "// One class per line; null means the release does not have it. A parameter ending in \"?\" is optional.\n\n"
    . "return [\n    'sources' => " . $literal($found) . ",\n    'classes' => [\n" . implode("\n", $lines) . "\n    ],\n];\n";
file_put_contents(__DIR__ . "/$major.php", $php);
echo "wrote $major.php: " . count(array_filter($surfaces)) . ' of ' . count($surfaces) . " classes found\n";
